version: '3'

services:
  web:
    build: .
    working_dir: /django_beginner_apps/
    command: python3 ./$PROJECTNAME/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django_beginner_apps
    ports:
      - "8000:8000"
