version: '3'

services:
  web:
    build: .
    working_dir: /django_beginner_apps/$PROJECTNAME/
    command: gunicorn -b 0.0.0.0:8000 django_jon_project.wsgi

    # remember to remove volumes or comment out when deploying to production
    volumes:
      - .:/django_beginner_apps
    env_file:
      - .env
    #networks:
    #  - nginx

  nginx:
    build: ./nginx
    ports:
      - "8000:80"
    #volumes:
    # Not needed since we are serving statci files from Amazon s3
    #  - ./$PROJECTNAME/project_static/:/webserver/static_content/
    depends_on:
      - web
    #networks:
    #  - nginx

  db:
    build: ./postgres
    hostname: db
    volumes:
      - ./postgres/postgres_data:/var/lib/postgresql/data/

#networks:
  #nginx:
    #driver: bridge
